version: '3.4'

services:
  employeedb:
    image: mongo

  workscheduledb:
    image: postgres

  payrolldb:
    image: mongo

  employee.api:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: src/Services/Employee/Employee.API/Dockerfile

  workschedule.api:
    image: ${DOCKER_REGISTRY-}workscheduleapi
    build:
      context: .
      dockerfile: src/Services/WorkSchedule/WorkSchedule.API/Dockerfile

  payroll.api:
    image: ${DOCKER_REGISTRY-}payrollapi
    build:
      context: .
      dockerfile: src/Services/Payroll/Payroll.API/Dockerfile

volumes:
  mongo_data:
  postgres_data: