version: '3.4'

services:
  employeedb:
    container_name: employeedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db/employee

  payrolldb:
    container_name: payrolldb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db/payroll

  worktimetrackerdb:
      container_name: worktimetrackerdb
      restart: always
      ports:
        - "27019:27017"
      volumes:
        - mongo_data:/data/db/worktimetracker

  workscheduledb:
    container_name: workscheduledb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ScheduleDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  employee.api:
    container_name: employee.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://employeedb:27017"
    depends_on:
      - employeedb
    ports:
      - "8000:80"

  workschedule.api:
    container_name: workschedule.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=workscheduledb;Port=5432;Database=ScheduleDb;User Id=admin;Password=admin1234"
    depends_on:
      - workscheduledb
    ports:
      - "8001:80"

  payroll.api:
    container_name: payroll.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://payrolldb:27017"
      - "GrpcSettings__WorkTimeTrackerUrl=http://worktimetracker.grpc"
    depends_on:
      - payrolldb
    ports:
      - "8002:80"

  worktimetracker.grpc:
    container_name: worktimetracker.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://worktimetrackerdb:27017"
    depends_on:
      - worktimetrackerdb
    ports:
      - "8003:80"
